version: '3.4'

services:
  mysql-inventory:
    platform: linux/x86_64
    image: mysql:8.2
    volumes:
      - inventory-db-data:/var/lib/mysql
      - ./app/inventory/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: inventory
      MYSQL_PASSWORD: inventory
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "3308:3306"

  redis:
    image: redis:7.0
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - session-data:/data
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    platform: linux/x86_64
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    volumes:
      -  zookeper-data:/var/lib/zookeeper/data
      -  zookeper-datalog:/var/lib/zookeeper/log

  broker:
    image: confluentinc/cp-kafka:7.4.3
    hostname: broker
    ports:
      - "19092:19092"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'
    volumes:
      - broker-data:/var/lib/kafka/data

  # This "container" is a workaround to pre-create topics
  kafka-setup:
    image: confluentinc/cp-kafka:7.4.3
    hostname: kafka-setup
    container_name: kafka-setup
    depends_on:
      - broker
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server broker:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:9092 --create --if-not-exists --topic inventory-vehicles-car --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server broker:9092 --list
      "

volumes:
  inventory-db-data:
  session-data:
  zookeper-data:
  zookeper-datalog:
  broker-data:
