CREATE DATABASE IF NOT EXISTS inventory;

CREATE USER IF NOT EXISTS 'inventory'@'%' IDENTIFIED BY 'inventory';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `inventory`.* TO 'inventory'@'%';